title: "Fabricatorz"
exclude: [README.md, LICENSE.md]

tagline: "We are a design & technology company"
description: "Fabricatorz - We are a design & technology company."
keywords: ['fabricatorz', 'design', 'technology']

repository: "https://github.com/Fabricatorz/fabricatorz.com"

piwik_site_id: 1

instagram:
  tag: 'fabricatorz'
  client_id: 'b30c56db9a884288af1e1c12fb6c34a1'
  captions: true
  limit: '20'
  refresh: '300000'
